[package]
name = "notes-service"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "*"
diesel = { version = "*", features = ["postgres", "r2d2"] }
dotenv = "*"
r2d2 = "*"
serde = "*"
